New folder/MyStore/MyStore/Areas/Admin/Controllers/AdminPanelController.cs
using Microsoft.AspNet.Identity.EntityFramework;
using MyStore.Entity;
using MyStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MyStore.Areas.Admin.Controllers
{
    [Authorize(Roles ="Admin")]
    public class AdminPanelController : Controller
    {
        private ApplicationDbContext _context;
        private readonly ApplicationUserManager adminUsermanager;
        public AdminPanelController()
        {
            _context = new ApplicationDbContext();

            adminUsermanager = new ApplicationUserManager(new UserStore<ApplicationUser>(_context));
        }
        [HttpGet]
        public ActionResult CreateCategory()
        {

            return View();
        }
        [HttpPost]
        public ActionResult CreateCategory(Category category)
        {
            _context.MyCategorys.Add(category);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
        // GET: Admin/AdminPanel
        public ActionResult Index()
        {

            return View();

        }
        [HttpGet]
        public ActionResult CreateRole()
        {

            return View();
        }
        [HttpPost]
        public ActionResult CreateRole(Role newRole)
        {
            _context.Roles.Add(new IdentityRole { Name = newRole.Name });
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult EditUserRole()
        {
            var allUser = _context.Users.ToList();
            var allRoles = _context.Roles.ToList();
            var allUseraNdRole = new UsersAndRoleViewModel
            { allRole = allRoles, allUser = allUser };
            return View(allUseraNdRole);
        }
        [HttpPost]
        public async Task<ActionResult> EditUserRole(string userName,string role)
        {
            var newRole = _context.Roles.First(x => x.Name == role);
          var currentUser=  _context.Users.First(x => x.UserName == userName);
            var currentRole = _context.Set<IdentityUserRole>().FirstOrDefault(x => x.UserId == currentUser.Id).RoleId;
            //var currentUser = _context.Users.Where(x => x.UserName == model.allUser[0].UserName);
            await adminUsermanager.RemoveFromRoleAsync(currentUser.Id, currentRole);
            await adminUsermanager.AddToRoleAsync(currentUser.Id, newRole.Name);
            //_context.Set<IdentityUserRole>().FirstOrDefault(x => x.UserId == currentUser.Id).RoleId = newRole.Id;
            _context.SaveChanges();
            
            return RedirectToAction("Index");

        }
        public ActionResult Admin()
        {

           


            //var adminID = _context.Roles.FirstOrDefault(x => x.Name == "Admin").Id;
            //var MyUsers = new List<AllUser>();
            //foreach (var item in allUser)
            //{
            //    var statusRole = _context.Set<IdentityUserRole>().FirstOrDefault(x => x.UserId == item.Id && x.RoleId == adminID);
            //    if (statusRole != null)
            //    {
            //        MyUsers.Add(new AllUser
            //        {
            //            Email = item.UserName,
            //            IsAdmin = true
            //        });
            //    }
            //    else
            //    {
            //        MyUsers.Add(new AllUser
            //        {
            //            Email = item.UserName,
            //            IsAdmin = false
            //        });
            //    }
            //}

            return RedirectToAction("Index");
        }
    }
}

New folder/MyStore/MyStore/Areas/Admin/Views/AdminPanel/CreateCategory.cshtml
@model MyStore.Entity.Category

@{
    ViewBag.Title = "CreateCategory";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>CreateCategory</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

New folder/MyStore/MyStore/Areas/Admin/Views/AdminPanel/CreateRole.cshtml
@model MyStore.Models.Role
@{
    ViewBag.Title = "CreateRole";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div class="container"></div>
<div class="form-group">
    @using (Html.BeginForm("CreateRole", "AdminPanel", FormMethod.Post))
    {

        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(x => x.Name)
        </div>




        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    }
</div>













    @*<div class="container">
        <div class="form-group">
            <label for="role">Role name</label>
            <div class="col-md-10">
                <input name="role" id="role" type="text" />
            </div>
              @Html.ActionLink("CreateRole", "AdminPanel",new { }, new { @class = "btn btn-primary MyStyleForBttn" })

        </div>
    </div>*@

New folder/MyStore/MyStore/Areas/Admin/Views/AdminPanel/EditUserRole.cshtml
@*@model MyStore.Models.UsersAndRoleViewModel*@
@{
    ViewBag.Title = "EditUserRole";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}



    <div class="container">
        @foreach (var item in Model.allUser)
        {
            <div class="row">

                @using (Html.BeginForm("EditUserRole", "AdminPanel", new { userName = item.UserName }, FormMethod.Post))
                {
                    <div class="col-md-6">
                        <h2>User Email:</h2>
                        <p>
                            @item.UserName
                        </p>
                    </div>

                    <div class="col-md-6 my-mr-top">
                        <div>
                            <h2>User Role:</h2>
                            <select id="role" name="role" class="MySelectionClass">
                                @foreach (var anotherItem in Model.allRole)
                                {
                                    
                                    @*if (item.Role.Equals(anotherItem))
                                    {
                                        <option selected>@anotherItem.Name</option>

                                    }
                                    else
                                    {*@
                                        <option>@anotherItem.Name</option>
                                   
                                }
                            </select>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>

        }
    </div>

New folder/MyStore/MyStore/Areas/Admin/Views/AdminPanel/Index.cshtml
@model  MyStore.Models.UsersAndRoleViewModel
@{
    ViewBag.Title = "Admin";
}

@Html.Partial("Partial/_AdminPanelPartial")