New folder/MyStore/MyStore/Areas/Manager/Controllers/ManagerController.cs
using MyStore.Areas.Manager.ImageClass;
using MyStore.Entity;
using MyStore.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Imaging;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace MyStore.Areas.Manager.Controllers
{
    public class ManagerController : Controller
    {
        private ApplicationDbContext _context;
        public ManagerController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Manager/Manager
        public ActionResult Index()
        {
            string id =ConfigurationManager.AppSettings["ManagerId"].ToString();

            var managerNews = _context.MyNews.Where(x => x.ManagerId == id).ToList();

            return View(managerNews);
        }
        [HttpGet]
        public ActionResult CreateNews()
        {
            ViewBag.Categories = _context.MyCategorys.ToArray();
            return View();
        }
        public ActionResult Return()
        {
            return RedirectToAction("LogOff", "Account");
        }
        [HttpPost]
        public ActionResult CreateNews(News news, HttpPostedFileBase imageFile)
        {
            news.Pfoto = CreateBitmap(imageFile);
            news.ManagerId = ConfigurationManager.AppSettings["ManagerId"].ToString();
            news.PostDate = DateTime.Now;
            news.NewsCategory = _context.MyCategorys.Where(x => x.Name == news.Categorie).ToArray()[0];
            _context.MyNews.Add(news);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult LogOff()
        //{
        //    AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
        //    return RedirectToAction("Index", "Home");
        //}
        public string CreateBitmap(HttpPostedFileBase imageFile)
        {
            string fileName = Guid.NewGuid().ToString() + ".jpg";
            string fullPathImage = Server.MapPath(Config.NewsImagePath) + "\\" + fileName;
            using (Bitmap bmp = new Bitmap(imageFile.InputStream))
            {
                var readyImage = ImageWorker.CreateImage(bmp, 450, 450);
                if (readyImage != null)
                {
                    readyImage.Save(fullPathImage, ImageFormat.Jpeg);
                   
                }
            }
            return fileName;
        }
    }
}

New folder/MyStore/MyStore/Areas/Manager/Views/Manager/CreateNews.cshtml
@model MyStore.Entity.News

@{
    ViewBag.Title = "CreateNews";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}

<h2 class="text-center">CreateNews</h2>

@using (Html.BeginForm("CreateNews","Manager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group ">
        @Html.LabelFor(model => model.NewsCategory, htmlAttributes: new { @class = "control-label col-md-2 my-mr-top" })
        @Html.ValidationMessageFor(x => x.NewsCategory)

        <div class="col-md-10">
            <label for="Categorie">Select Categories</label>
            <select id="Categorie" name="Categorie" class="form-control">
                <option selected></option>
                @foreach (var item in ViewBag.Categories)
                {
                    <option>
                        @item.Name
                    </option>
                }
            </select>
            @Html.ValidationMessageFor(x => x.Pfoto)
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Image</label>
        <div class="col-md-10">
            <input type="file" name="imageFile" />
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

New folder/MyStore/MyStore/Areas/Manager/Views/Manager/Index.cshtml
@model IEnumerable<MyStore.Entity.News>
@{
    ViewBag.Title = "Index";
}

@if (Model.Count() == 0)
{
    <div>
        <h2 class="text-center text-uppercase text-danger">You does not having news</h2>
    </div>
    <div class="container">

        @Html.ActionLink("New news", "CreateNews", new { @class = "btn btn-primary" })

    </div>
}
else
{
    <div class="container">

        @Html.ActionLink("New news", "CreateNews", new { @class = "btn btn-primary btn-lg" })

    </div>
    <h1 class="text-center">Your news</h1>
    <div class="container text-center">
        @foreach (var item in Model)
        {
            <article class="">
                <div class="card ManagerNewsPosition">
                    <div class="row ">
                        <div class="col-md-3">
                            <img src="../../../../Images/News/@item.Pfoto" width="135" class="card-img " alt="...">
                        </div>
                        <div class="col-md-6 my-flexAlign">
                            <div class="card-body">
                                <h3 class="card-title text-red">@item.Name</h3>
                                @if (item.NewsCategory != null)
                                {<p class="card-text">@item.NewsCategory.Name</p>
                            }
                                <p class="card-text">@item.PostDate.ToLongDateString()</p>

                            </div>
                        </div>
                        <div class="col-md-3 my-flexAlign">

                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-primary MyStyleForBttn" })
                            @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-primary MyStyleForBttn" })
                        </div>
                    </div>
                    <a href="~/Areas/Manager/Views/Manager/Index.cshtml">~/Areas/Manager/Views/Manager/Index.cshtml</a>
                </div>
            </article>
        }
    </div>
}